services:
  - type: web
    name: hr-system
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true

